
package mx.com.nmp.mspreconciliacion.centropagos.consumer.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "xmltransaccionesPortType", targetNamespace = "http://wstrans.cpagos")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface XmltransaccionesPortType {


    /**
     * 
     * @param in5
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://wstrans.cpagos")
    @RequestWrapper(localName = "transaccionesCargosAutomaticos", targetNamespace = "http://wstrans.cpagos", className = "cpagos.wstrans.TransaccionesCargosAutomaticos")
    @ResponseWrapper(localName = "transaccionesCargosAutomaticosResponse", targetNamespace = "http://wstrans.cpagos", className = "cpagos.wstrans.TransaccionesCargosAutomaticosResponse")
    public String transaccionesCargosAutomaticos(
        @WebParam(name = "in0", targetNamespace = "http://wstrans.cpagos")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://wstrans.cpagos")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://wstrans.cpagos")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://wstrans.cpagos")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://wstrans.cpagos")
        String in4,
        @WebParam(name = "in5", targetNamespace = "http://wstrans.cpagos")
        String in5);

    /**
     * 
     * @param in5
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://wstrans.cpagos")
    @RequestWrapper(localName = "transaccionesDomiciliacion", targetNamespace = "http://wstrans.cpagos", className = "cpagos.wstrans.TransaccionesDomiciliacion")
    @ResponseWrapper(localName = "transaccionesDomiciliacionResponse", targetNamespace = "http://wstrans.cpagos", className = "cpagos.wstrans.TransaccionesDomiciliacionResponse")
    public String transaccionesDomiciliacion(
        @WebParam(name = "in0", targetNamespace = "http://wstrans.cpagos")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://wstrans.cpagos")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://wstrans.cpagos")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://wstrans.cpagos")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://wstrans.cpagos")
        String in4,
        @WebParam(name = "in5", targetNamespace = "http://wstrans.cpagos")
        String in5);

    /**
     * 
     * @param in5
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://wstrans.cpagos")
    @RequestWrapper(localName = "transacciones", targetNamespace = "http://wstrans.cpagos", className = "cpagos.wstrans.Transacciones")
    @ResponseWrapper(localName = "transaccionesResponse", targetNamespace = "http://wstrans.cpagos", className = "cpagos.wstrans.TransaccionesResponse")
    public String transacciones(
        @WebParam(name = "in0", targetNamespace = "http://wstrans.cpagos")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://wstrans.cpagos")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://wstrans.cpagos")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://wstrans.cpagos")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://wstrans.cpagos")
        String in4,
        @WebParam(name = "in5", targetNamespace = "http://wstrans.cpagos")
        String in5);

    /**
     * 
     * @param in5
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://wstrans.cpagos")
    @RequestWrapper(localName = "cancelacionesCargosAutomaticos", targetNamespace = "http://wstrans.cpagos", className = "cpagos.wstrans.CancelacionesCargosAutomaticos")
    @ResponseWrapper(localName = "cancelacionesCargosAutomaticosResponse", targetNamespace = "http://wstrans.cpagos", className = "cpagos.wstrans.CancelacionesCargosAutomaticosResponse")
    public String cancelacionesCargosAutomaticos(
        @WebParam(name = "in0", targetNamespace = "http://wstrans.cpagos")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://wstrans.cpagos")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://wstrans.cpagos")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://wstrans.cpagos")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://wstrans.cpagos")
        String in4,
        @WebParam(name = "in5", targetNamespace = "http://wstrans.cpagos")
        String in5);

}
